### ISSUE TITLE
Optionally remove scrollability of tabs.

### ISSUE THREAD

**Issue by geheur** [geheur/bank-tag-custom-layouts#10]
Having the tags be always scrollable, which is something this plugin does, has some annoyances:

* It makes it difficult to drag items near the bottom of the visible area without scrolling the container.
* If you accidentally drag an item that is slightly off-screen, it will scroll the container (less of an issue but still kinda inconvenient).
* The visual clutter of a not always wanted scrollbar.

However, for people to lay their tags out however they want, it is useful to always have the container be scrollable. Unlike regular bank tag tabs, this plugin allows for empty space, and it's impossible therefore to determine how much space a tag should take up, because I can't predict how much empty space people want. Therefore, a problem arises: how do people add extra empty space at the end of their tab when they need it, without the aforementioned scrolling issues?

Possible solutions:
* Make scrollability a toggle. People can go to the config if they really need to add extra rows to a tag tab, and then disable it again once they've set up their tab. I think few people even use any space below the visible area of a tag, because scrolling is annoying and most tags do not even contain enough items, even after accounting for empty space. So very few people will even be inconvenienced at all.
* + row button - a button that adds an extra row to the container. This sounds like annoying visual clutter.

**Comment by geheur** [comment]
Scrollability also makes it possible to "lose" an item below the visible area.

**Comment by geheur** [comment]
I can just make it so that dragging an item below the bank window extends the space. Problem solved, and super easy implementation too. Don't even really need a toggle anymore. I'm sure anyone who needs this can figure it out.

**Comment by geheur** [comment]
Added in v1.2.1.

**Comment by mjneil** [comment]
> I can just make it so that dragging an item below the bank window extends the space. Problem solved, and super easy implementation too. Don't even really need a toggle anymore. I'm sure anyone who needs this can figure it out.

@geheur this doesn't seem to work anymore. I like to use a lot of empty space and organize vertical in some tags, but now I can't to increase the height of a tag. Any chance you can look into this?

**Comment by mjneil** [comment]
hmm that is really strange, I wish I knew when it stopped working for me
