### ISSUE TITLE
Make this work with the Inventory Setups plugin.

### ISSUE THREAD

**Issue by geheur** [geheur/bank-tag-custom-layouts#2]
This plugin should detect when the bank is being filtered by the Inventory Setups plugin, so that custom layouts can be set.

I think using the bank title is the best way to detect this, since the Inventory Setups plugin modifies this when it is filtering the bank.

Should I require custom layouts to be enabled for these inventory setups? I'm already not 100% sure doing that for regular tabs was the best idea, and I'm also not sure how to let people configure whether the custom layout should be enabled for a particular inventory setups. A checkbox in the config to enable this (probably set to true by default) would be good enough, I assume.

**Comment by geheur** [comment]
Should it be possible to import/export layouts for these?

**Comment by MathieuDR** [comment]
I would love this feature. I mainly use inventory setups.

Besides using Inventory Setups + Bank Tag custom layouts, there is a bug when opening the bank.

I've added an image for if you're using both plugins. A tab is active (from previous bank-attendance or clicking it whilst you're using the bank) and an inventory setup is active.

Most of the items aren't in the 'teleport tab', but are from the inventory setup. Yet the placeholders makes it a bit difficult to use the inventory setup plugin.

![img](https://i.imgur.com/rLoiBTu.png)

**Comment by geheur** [comment]
@MathieuDR  how exactly are you making this happen? I've made it happen before but either it only happens randomly or I've forgotten how I did it last time.

**Comment by geheur** [comment]
This is a Runelite bug (source: Runelite discord). Will probably be fixed next time Runelite updates.

**Comment by geheur** [comment]
An initial version of this feature exists on branch inventory-setups-support. Before publishing this, I'd like to add auto-layout to this, based on the contents of the inventory setup.

**Comment by geheur** [comment]
PR is finally open! https://github.com/runelite/plugin-hub/pull/1331

No import/export currently exists, would like this to be done by Inventory Setups rather than by my plugin, as it's more convenient.

Also there is currently no way to transfer layouts between bank tags and inventory setups.

**Comment by geheur** [comment]
PR has been accepted. Closing this issue and making new ones for the remaining work.
