### ISSUE TITLE
Re-ordering items inside the inventory setups layout is re-ordering actual bank tabs

### ISSUE THREAD

**Issue by ryan-abbott26** [geheur/bank-tag-custom-layouts#25]
When using the invetory setups plugin with layouts enabled, dragging items around will re-order them in the default Jagex bank tabs.

**Comment by ryan-abbott26** [comment]
![bug](https://user-images.githubusercontent.com/82670125/115055662-a5b31180-9ed9-11eb-9965-196148b2bc66.gif)

**Comment by geheur** [comment]
Fixed on master.

**Comment by geheur** [comment]
The PR is merged, this fix should now be live.
