### ISSUE TITLE
Layout Enables - Wont Disable?

### ISSUE THREAD

**Issue by madaraxuchiha** [geheur/bank-tag-custom-layouts#28]
After clicking the icon in bottom right of a tab to "Preview Auto Layout" it no longer has the ability to disable the auto layout any longer. Screenshots attached of what happens after, the only way to revert back to original setup is to turn off the plugin.

![1](https://user-images.githubusercontent.com/48638389/115240725-626bd380-a163-11eb-9513-1ebec9cd9267.PNG)

![2](https://user-images.githubusercontent.com/48638389/115240727-639d0080-a163-11eb-81f1-a24feef4de64.PNG)

**Comment by madaraxuchiha** [comment]
Clicking the icon again and selecting "cancel preview" doesnt revert it back to normal either.

![image](https://user-images.githubusercontent.com/48638389/115240952-9c3cda00-a163-11eb-8808-e6bf36fdd038.png)

**Comment by geheur** [comment]
Does selecting another tab and then going back to the tab with the issue fix it?

Also, was layout enabled on this tab before you used auto-layout?

**Comment by madaraxuchiha** [comment]
Nope, every time closing bank, changing tab, etc and returning it is enabled. And no, layout wasn't enabled on the tab.

If it helps, I can share screen in discord so you can have a better look.

**Comment by madaraxuchiha** [comment]
Logged in and had a look this morning, seems to have reverted itself now. Unable to replicate it at this point, will keep you posted.

**Comment by geheur** [comment]
I know of a bug which sounds similar but it fixes itself when you change to another tab and then return back.
