### ISSUE TITLE
withdrawing/depositing bug

### ISSUE THREAD

**Issue by purush97** [geheur/bank-tag-custom-layouts#3]
Withdrawing or depositing items appears to completely mess up the tab https://streamable.com/5t1ut3

**Comment by geheur** [comment]
Temporary fix is to disable "Remove tab separators" in "Bank Tags Plugin".

I've already fixed this issue, will close this issue once that is live.

**Comment by purush97** [comment]
Thank you :) Love the plugin btw, already probably one of my favourites!

**Comment by geheur** [comment]
v1.1 is now live; closing this issue.
