### ISSUE TITLE
Cannot rearrange items when the title of an Inventory Setup contains a colon

### ISSUE THREAD

**Issue by SLAMDANK420** [geheur/bank-tag-custom-layouts#35]
For example I have an inventory setup titled "Iron Medium Clues: Imps", and I was unable to rearrange the items until I replaced the colon with a comma. There may be other characters that can cause the same problem.

**Comment by OzzyCallooh** [comment]
Thank you for reporting this bug; this was driving me nuts! Maybe this has something to do with filenames, since Windows filenames can't contain colons (something about file streams?)

**Comment by geheur** [comment]
it's probably because colons are a special character in the saved layouts and since colons are not allowed in bank tag names I didn't bother escaping them.

**Comment by geheur** [comment]
Should be fixed in 1.4.11.
