### ISSUE TITLE
Inventory Setups integration is broken

### ISSUE THREAD

**Issue by justin-nierendorf** [geheur/bank-tag-custom-layouts#39]
![image](https://user-images.githubusercontent.com/33694916/137662467-301bcc3c-0515-43bf-9186-5497ad3dce92.png)

Everything seemed to kind of break when I clicked "Remove item from slot" on one of the items in an inventory setup. Now I can't move items around, or withdraw anything. When I right click some items it looks like the picture above.

I've tried uninstalling and reinstalling the plugin and that didn't help things. I'm nervous about uninstalling/reinstalling Inventory setups because I have 30+ setups I use and I don't want to lose that data.

Using this plugin without Inventory Setups seems to work fine, and using Inventory Setups without this plugin also seems to work fine. Let me know if you want any more info

**Comment by ckwong95** [comment]
Experiencing this issue as well. It seems to be caused by an overlap of duplicate items over the current items in bank.
