### ISSUE TITLE
clue scrolls should not be variant cross-difficulty.

### ISSUE THREAD

**Issue by geheur** [geheur/bank-tag-custom-layouts#41]

**Comment by Wynadorn** [comment]
Why not? What if you have multiple clue scrolls banked. I think they should remain as 6 separate items.

**Comment by geheur** [comment]
I don't know what you mean. Currently all clue scroll difficulties are grouped in one group in runelite's ItemVariationMapping and this makes it impossible to consistently place different clue difficulties in different spots in the bank - it will be based off of the order they are in in your regular bank. This is bad and I don't like it.

**Comment by Wynadorn** [comment]
Ooooh I see, I misunderstood 👍

**Comment by geheur** [comment]
dupe #13.
