### ISSUE TITLE
"Presets" layout behaves poorly with (some?) Inventory Setups

### ISSUE THREAD

**Issue by zdunbrack** [geheur/bank-tag-custom-layouts#50]
Not really sure how to title this, but using the new "presets" layout has very confusing behavior. I'm guessing it works in some ideal conditions, but runs into issues. @Micrococonut I know this was your change, not sure if you can provide any insight. I figure that it might have to do with some assumptions that the zigzag auto-layout makes (e.g. no empty inventory spaces, not sure how it handles fuzzy, etc.)

Inventory Setup: https://i.imgur.com/IdqyTkZ.png

Previewed layout: https://imgur.com/a/SOOxIrl

Honestly, there are all sorts of things that could be the culprit here, but the behavior is downright baffling at first glance. I discovered this because I really like the potential of arbitrary presets (personally, my setup currently looks like [this](https://imgur.com/pcjXNYo)) and wanted to allow users to create their own custom auto-layout options.

From my testing, working with tag tabs behaved fine, but most if not all of my inventory setups went awry. Specifically, it looks like the ammo, ring, glove, bottom, and boot slots are consistently going into incorrect positions for the armor, and empty spaces are ignored in the inventory section. I might try to look into the code and figure out what's going on tomorrow, but this is less than ideal behavior.

Edit: updated images to be embedded links because 4k screen = large images on Github

**Comment by Micrococonut** [comment]
This seems to be the result of some poor assumptions I made when writing the inventory setups compatibility. I will look into a proper solution

**Comment by Micrococonut** [comment]
Fixed in this PR #51

**Comment by Micrococonut** [comment]
@geheur can we close this issue

**Comment by geheur** [comment]
yeah.
