### ISSUE TITLE
tabs not saving

### ISSUE THREAD

**Issue by mcbridel** [geheur/bank-tag-custom-layouts#54]
tabs arent saving, maybe this is because im multi logging, can you reccomend a way to make it save if you know how

**Comment by geheur** [comment]
I think the only way to make sure it saves is to close the runelite client that has the changes you want saved after you close all other clients.

Runelite does not have any support for having your savedata work intuitively with multiple instances of the clients, other than having each client use a completely separate set of saveadata, which I doubt is what you want.
