### ISSUE TITLE
clues dont appear

### ISSUE THREAD

**Issue by pettrs** [geheur/bank-tag-custom-layouts#57]
when i get any new clue, it doesn't appear in my bank tags, i have to re-drag it. this does not seem to happen on mastre clues for some reason

https://user-images.githubusercontent.com/75093127/169700603-bdf0f9fb-4e7e-49f3-86f6-d9e1ee00f20f.mp4

?

**Comment by geheur** [comment]
that's because master clues are all the same item id (beginners also). You need to hold shift when you drag the clue onto the tab then it will use the bank tag plugin (not bank tag layout) item variation feature so that all clue scrolls end up in the tab.
