### ISSUE TITLE
Please add Folders

### ISSUE THREAD

**Issue by ETalanian** [geheur/bank-tag-custom-layouts#58]
Hello,  I absolutely LOVE this plugin, but as I add more and more tabs, the more I would love to have folders.  I imagine it being in the same spot as the current Bank Tag Tabs, but you click and it opens a horizontal menu with the Tag Tabs that you have in this folder.  This would make organizing Bank Tag Tabs so much easier by being able to categorize them by things like Slayer, Bossing, Clues, Minigames, etc.  Thanks in advance!

**Comment by geheur** [comment]
hmm that sounds tricky because that menu is from Bank Tags (the vanilla runelite plugin) not Bank Tag Layouts. I probably wouldn't add this.

One thing that might help you though is the "tag tab tab", right-click the button in the top left of the bank with the "+" on it and click "View tag tabs".

**Comment by ETalanian** [comment]
Unfortunate to hear, but I'll definitely make use of the tag tab tab, thanks!
