### ISSUE TITLE
Yet another Inventory Setups compatibility issue

### ISSUE THREAD

**Issue by Nightfirecat** [geheur/bank-tag-custom-layouts#59]
Per the title, the layout seems semi-broken for certain setups. It is *mostly* right, but has some items out of place and blank spots in the wrong place for several others.

Notably:
* While rune pouch runes are correctly shown separately, the zamorak monk robe and sharks are not in the right spot
* There's random blank spots in the layout which shouldn't be there
* The anglerfish should be in the first blank spot (row 3 column 5) but appears too early
* There's meant to be two bastion potions in the layout, but only one is shown

Layout:
![Screenshot_20220807_211345](https://user-images.githubusercontent.com/2199511/183337757-f004a04e-4f18-44fa-9b41-e954f56ba505.png)

Inventory setup:
![Screenshot_20220807_211411](https://user-images.githubusercontent.com/2199511/183337811-28c4b32e-6caa-4401-84c4-ab588b5343f5.png) ![Screenshot_20220807_211434](https://user-images.githubusercontent.com/2199511/183337854-ca701b7e-aca6-4d2e-8f21-026737caaa34.png)

Settings: (for both plugins)
![Screenshot_20220807_211503](https://user-images.githubusercontent.com/2199511/183337900-cc0778cd-b3a4-4d1f-934e-d9b3167b88c6.png) ![Screenshot_20220807_211553](https://user-images.githubusercontent.com/2199511/183337982-470486bd-bf55-4929-b669-47b62cdfc0b9.png)

**Comment by Nightfirecat** [comment]
I realize this is caused by / duplicate of #37, as dragging any item in a setup's layout causes the layout to completely break down when trying to add or adjust existing items until the auto-layout button is used to replace it. (Why are setup layout items draggable at all? Why does it not recreate the layout when reopening the setup with the bank open?) Without re-enabling `Auto Layout button`, there is no indication of how to fix it.

**Comment by geheur** [comment]
yeah there's a bunch of issues with auto-layout. It kind of needs a rewrite :(
