### ISSUE TITLE
Different layouts per account

### ISSUE THREAD

**Issue by Zamua** [geheur/bank-tag-custom-layouts#63]
Hello, this may be user error so please correct me if so.

I am using jagex launcher + runelite on macOS. currently all accounts I login with have the same backtabs and layouts. It would be nice if I could have account specific ones. The layouts I make to pk on a pure aren’t useful when I’m logged in on my main

thanks!

**Comment by geheur** [comment]
This would be harder to add than it sounds because this plugin is built on top of the bank tags plugin which I do not control, and it does not support per-osrs-account tags.

Currently your best option may be https://github.com/runelite/runelite/wiki/General-Features#playing-with-multiple-accounts

**Comment by Zamua** [comment]
aha yes you're right, and thanks for the suggestion! i will poke around the bank tags plugin code

**Comment by geheur** [comment]
Closing this because of the bank tags thing and also because any solution would look different due to profiles. and because of profiles idk how many people even want this.
