### ISSUE TITLE
Degraded Barrows and Partially Charged Jewelry no longer work with layouts

### ISSUE THREAD

**Issue by neilmehta-leapyear** [geheur/bank-tag-custom-layouts#64]
![image](https://user-images.githubusercontent.com/88852425/207331443-cd611124-48ac-4982-af28-e9c3868d7850.png)

When Barrows items degrade (i.e. from 75 -> 50) or when partially charged jewelry gets used (i.e. Digsite pendent 3 -> 2) the layout for the item no longer works and need to be removed/re-added each time

**Comment by geheur** [comment]
This sounds like you need to variation tag this in bank tags plugin e.g. by holding shift when you drag the item onto the bank tag tab.
