### ISSUE TITLE
Rune pouch problems

### ISSUE THREAD

**Issue by RsFoe** [geheur/bank-tag-custom-layouts#68]
Every time I make a setup with 'auto layout' if my runepouch has runes inside of it the layout automatically adds all of those runes into the layout. Theres a lot of setups where I dont want a runepouch in it and or runes. The only way to rectify it is always emptying rune pouch or just removing it after using the auto button which is very tedious. I have confirmed other people have the same issue and couldnt find a setting to change the behavior.

**Comment by geheur** [comment]
Added in 4da5dbda9163c6d289287f77325fe0d540266e20 - runes are not added unless there is a rune pouch in the inventory. To be released in whatever version is after 1.4.19 (probably 1.4.20).
