### ISSUE TITLE
Compatibility issue with Runelite's plugin profiles feature

### ISSUE THREAD

**Issue by OskarOskar** [geheur/bank-tag-custom-layouts#70]
I noticed a bug when switching between Runelite profiles [(added in 1.9.11)](https://runelite.net/blog/show/2023-02-18-1.9.11-Release). The bank tag layout will be reset after switching to a profile which doesn't have the bank tag.

Let's say you have a default profile with no bank tag.
You duplicate the default (or create a new one), and then make a bank tag on that profile. Then customize the layout with this plugin.
If you switch to the default profile, and back to the new one. The bank tag will still be there but the layout is reset - with every item moved to the top of the page.

**Comment by geheur** [comment]
fyi the bank tags plugin also does not handle profiles properly - it is in an invalid state after a profile change until you open the bank again.

Also I cannot replicate what you described. My layout it still present. Is your bank open/is the bank tag selected while you are doing the profile changes?

**Comment by OskarOskar** [comment]
No I'm closing the bank, here's a video:
(profile 1 doesn't have the bank tag, only profile 2 does)

https://user-images.githubusercontent.com/6757518/222117938-257aff5b-c688-4511-b234-3015cbef52e5.mp4

Any ideas what else could be causing this to reset?

Here's my settings for Bank Tag Layouts:
![image](https://user-images.githubusercontent.com/6757518/222118460-138e889b-4134-40d1-b203-5dbadd92c3c2.png)
For the Bank Tags plugin I have all four settings enabled.

**Comment by geheur** [comment]
Still can't replicate this. Just to be sure, do *other* settings, such as for other plugins, save properly? There are some people who have had issues with the profiles update where they say stuff isn't saving.

**Comment by geheur** [comment]
Closing as stale. If you can find out how to make this happen feel free to re-open.

**Comment by OskarOskar** [comment]
Alright, I haven't been able to reproduce this again recently. Maybe something changed with the Runelite profile feature?

Fwiw. last time I could reproduce it, it seemed like the name of the profile (or bank tag name?) could have an effect.
Since the issue would stop happening if I created a new profile with a different name.
The issue would persist even if I deleted the profile that kept resetting and recreating it with the same name.

I had a hunch this might have something to do with duplicating a profile and then deleting the bank tag from the original profile. But I haven't been able to test this.

But I'm pretty sure that is what was happening in the clip I posted above:
- create bank tag with layout on "default" profile
- duplicate profile
- delete bank tag from default
- switch bank and fourth between original profile and the duplicated

**Comment by geheur** [comment]
Is it possible that this is from having 2 profile with very similar bank tags, but like, one different? When bank tag layouts sees a bank tags change like tag1,tag2,tag3 -> tag1,tag2, it interprets that as deleting tag3, so it deletes the layout. This can happen on a profile change.
