### ISSUE TITLE
(Quest speedrunning) graceful doesn't get tags applied to tab.

### ISSUE THREAD

**Issue by MystarB** [geheur/bank-tag-custom-layouts#73]
Normally when you click Preview auto layout, then click confirm it will tag every item in your inventory/equipped items with the tag of the tab you're looking at, however it does not get applied to the quest speedrunning graceful and you have to apply it manually to all 6 pieces. It does correctly show it in the layout, just you will not be able to withdraw by clicking on it, and are left with only the options Duplicate-item and Remove-layout.

I unfortunately do not own any other graceful anymore, so I'm unable to test if its an issue I'm only encountering the issue with this graceful.

**Comment by geheur** [comment]
I would guess this is an issue with runelite not being updated to include quest speedrunning graceful, since there is some odd behavior with weight reducing items. I'll see if I can get it added.

**Comment by geheur** [comment]
https://github.com/runelite/runelite/pull/16404

**Comment by geheur** [comment]
will be available in the next runelite update, probably 1.9.14.
