### ISSUE TITLE
Suggestion: Add option for default left click of the "+" tab to "View Tag Tabs"

### ISSUE THREAD

**Issue by jermdisc** [geheur/bank-tag-custom-layouts#76]
I think it would be a great addition to the plugin if we had the ability to simply left click that "+" tab and it go to the "View Tag Tabs" page, allowing us to find the appropriate layout quicker. Thank you for all of the work you have done with this plug in, it is wonderful.

**Comment by jermdisc** [comment]
Could you explain how it is done in the Custom menu swaps? I have been trying to figure out the correct wording but cannot seem to get it to work.

**Comment by geheur** [comment]
just add "view tag tabs" on its own line in the config for "custom swaps" at the top of the settings panel.

**Comment by jermdisc** [comment]
thank you very much
