### ISSUE TITLE
Inventory Setup label showing incorrectly

### ISSUE THREAD

**Issue by brandonmikelpaul** [geheur/bank-tag-custom-layouts#78]
<img width="982" alt="Screen Shot 2023-05-29 at 5 30 37 AM" src="https://github.com/geheur/bank-tag-custom-layouts/assets/42774805/8738fb08-032b-46b5-bceb-ca79c5615718">

Filtering is happening but layout is not organized correctly.

Is there an easy way to fix this?
<img width="234" alt="Screen Shot 2023-05-29 at 5 35 51 AM" src="https://github.com/geheur/bank-tag-custom-layouts/assets/42774805/a74cbcc1-9e39-4ee5-b157-2affee32976c">
<img width="245" alt="Screen Shot 2023-05-29 at 5 35 39 AM" src="https://github.com/geheur/bank-tag-custom-layouts/assets/42774805/8b8d55f1-c4ab-49e9-9f12-e8db895dd02c">

**Comment by geheur** [comment]
What exactly is wrong with it?
Maybe run the auto layout again?

**Comment by geheur** [comment]
Choose presets instead of zigzag I. The plugin's config.
