### ISSUE TITLE
"Fuzzy" toggle

### ISSUE THREAD

**Issue by Chryma** [geheur/bank-tag-custom-layouts#85]
There's another similar plugin that lets you toggle 'fuzzy' which is useful when for example you have the regular blowpipe and the new orn kit one from leagues, because currently when you attach the orn kit it removes it from the layout. Is there any way we can toggle fuzzy on an item, or is there an alternative way of doing what I'm doing without having to re-add the blowpipe to all my layouts?

**Comment by geheur** [comment]
If you mean inventory setups, that one probably doesn't recognize blazing blowpipe as fuzzy. It most likely uses runelite's variation items system, which has probably not been updated to include the blazing blowpipe as a blowpipe.

**Comment by Chryma** [comment]
So another example is that I have a different slayer helm but my layouts that I made with my old one are greyed out like this:
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/29678335/4f684177-b4bf-4cd7-98d0-6033dd99a704)

So I basically want it so that no matter what I do to my slayer helm it will still show up in all the layouts

**Comment by geheur** [comment]
did you variation tag the slayer helmet? (shift-drag it on the tag tab)

**Comment by Chryma** [comment]
I did not know that was a thing, that helps, is there any way to retroactively tag items like that or does it need to be done on the creation of the tab?

**Comment by geheur** [comment]
Just shift drag it onto the tab. it will add all the variations. you don't have to do it at creation. But it would be nice if e.g. autolayout automatically did it for some items. It just can't be done for all variation items, I would have to make a manual list of which items need to be handled like this.
