### ISSUE TITLE
Bank Tag categories/groups

### ISSUE THREAD

**Issue by DylanM05** [geheur/bank-tag-custom-layouts#87]
Would it be possible to add like a "Group" tag like for example:
I have a TOB tag, and in this TOB group I have 3 different tabs that drop down after I click it for melee/range/mage

**Comment by BrandonEnglish848** [comment]
Can I bump this? This would be amazing!

**Comment by geheur** [comment]
This is a bank tags plugin issue, not bank tag layouts.

Also, consider using the "view tag tabs" feature ("+" button in the top left of the bank, right click it)
