### ISSUE TITLE
Auto-Layout icon missing from tab UI

### ISSUE THREAD

**Issue by warfare32** [geheur/bank-tag-custom-layouts#89]
I'm not sure what changed in the recent updates. I went to create a new bank tab layout. I created the tab just fine and then realized the white 2 crossing arrow "auto preview" button to create the tab based on my characters loadout + inventory was no longer there. I tried restarting Runelite, and resetting the plugin. I have not yet tried uninstalling and reinstalling the plugin. I wasn't sure if it would delete all of my bank tabs if I did that so I haven't yet. 

In the settings it shows the Auto layout button is enabled, yet the button is no longer displayed. Any help is greatly appreciated.
![missing auto layout](https://github.com/geheur/bank-tag-custom-layouts/assets/52905877/49baefbd-beda-40e5-a615-6edf58fd7181)

**Comment by MrMark1127** [comment]
I thought I was going crazy, came to report the same issue. Glad it's not just me it seems. Reset Runelite entirely for myself, reinstalled the plugin and I'm still experiencing the issue. Enabled, disabled, tried to open and close the bank several times, even tried a different bank.

**Comment by Rahib0** [comment]
Preview button has disappeared for me as well. Tried resetting the Bank Tags and Bank Tags Layouts plugins the button is still missing.

**Comment by PartitionPixel** [comment]
Same thing here

**Comment by lukew0w** [comment]
Same problem here

**Comment by zytexa** [comment]
Same here

![image](https://github.com/geheur/bank-tag-custom-layouts/assets/51744054/c99c9cb4-6fac-4c9c-bbea-9daef6fbe39f)

**Comment by TheMightyTore** [comment]
Same problem here. anyone else use the Inventory Setups plugin? Was curious if something with that caused it as I only noticed it after I updated a setup in that plugin (tried disabling the "use with inventory setups" and disabling the plugin itself but still seeing the issue). I was able to use auto-layout fine yesterday

**Comment by PinkNanner** [comment]
Same issue here, also using inventory setups plugin
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/42795857/c56a0ce5-3faa-4e0d-bba6-2d789bf04594)

**Comment by Rikkert-Lensen** [comment]
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/44774241/02f983eb-4e75-415a-a395-d781bafdf2fc)
Same here

**Comment by Rikkert-Lensen** [comment]
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/44774241/e3e35921-0eaa-449f-8cc0-c17c86868739)
Same issue here

**Comment by joost00719** [comment]
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/21021559/b64f7a70-2861-4ec8-8622-1f675d4c93e2)
Same here

**Comment by MoralFiber** [comment]
I'm having the same exact issue as well.  No auto layout icon on the bottom right.

**Comment by JustMelloh** [comment]
Just waiting for the fixes to be pushed now I think he was working on it in the 14.2.24.

**Comment by luisespinosa3141** [comment]
yeah facing the same issue. I had it reappear for a second but it disappeared once I clicked out and back in my bank.

**Comment by warfare32** [comment]
It appears to be fixed. I'll mark this closed.

**Comment by MoralFiber** [comment]
Can confirm it is fixed.. thank you!
