### ISSUE TITLE
Info Stats and MousetoolTips & Scrollbar Issues

### ISSUE THREAD

**Issue by BabsCox** [geheur/bank-tag-custom-layouts#9]
The Bank Tag Layout is pulling in Info Stats and Mousetooltips that are turned off. See example: "Law Rune" which if I move to the traditional tab (not the bank tag) it does not include this tooltip/item info.

Additionally, the plugin was updated to include the scrollbar regardless of the # of items in the layout. Can this be adjusted to only be included if the number of items exceeds the available space, therefore requiring a scrollbar?

Prior to the recent update, the above was working as expected and no scroll bar was automatically ported.

![image](https://user-images.githubusercontent.com/81268914/112230211-e84f3a00-8c0a-11eb-8aaf-19f5834af977.png)

**Comment by geheur** [comment]
The tooltips are a bug I didn't notice and will be fixed in the next update
(though they will still show up on the layout placeholders unless you
toggle them off in config).

I was not aware that the scroll bar didn't use to be present. I've always
lazily just set the container height to 2000 to allow people to drag items
as far down as they want. When I get to my pc I can try to build an old
version and see if this is actually the case.

There is a bug related to scroll bar flickering when you withdraw an item
and that will also be fixed in next update.

**Comment by geheur** [comment]
Hang on so you're saying in a regular tab it doesn't show ge price of the
law runes? Cause idk what could be causing that part of the tooltips to
show up.

**Comment by BabsCox** [comment]
Hey, just the text in yellow - "Law Rune" in this case.

**Comment by geheur** [comment]
Loaded up what I think was the initially released version and I'm seeing a scrollbar.

![image](https://user-images.githubusercontent.com/41499327/112241646-e637ac00-8c07-11eb-97da-1b038b1cbbac.png)

Given that I don't recall ever seeing it without a scrollbar or ever making a change related to that, I'm gonna assume that's not something that has changed.

That said I don't mind removing it but... what if someone wants more space? kind of have to be able to scroll down for that.

**Comment by geheur** [comment]
Also any change you have a pic of what kind of setup that tab is supposed to put in your inventory? I'm looking to collect different ways of laying out tabs for #4.

**Comment by BabsCox** [comment]
The issue I'm seeing is that when you're clicking through to gear quickly, it stutters because of the available container height you've set. Whereas if the window is fixed, it doesn't perform that stutter. 

If someone needs additional space, my assumption would be you'd have to prepare a variable container height for when someone bring in too many items to fill the available space. That's how the traditional bank works. No scrollbar appears until you've taken up your currently available space. 

This lets you place items close to the withdraw/deposit item buttons while maintaining a fixed position so that you don't accidentally scroll and ruin that alignment.

**Comment by BabsCox** [comment]
> Also any chance you have a pic of what kind of setup that tab is supposed to put in your inventory? I'm looking to collect different ways of laying out tabs for #4.

The sample I provided was a turael task-skip that has the items fall into my inventory as I like them. A more suitable example would be the below nightmare gearing: 

![image](https://user-images.githubusercontent.com/81268914/112243520-18570700-8c24-11eb-849a-f80ded4ced82.png)


That resolves to:
![image](https://user-images.githubusercontent.com/81268914/112243563-2dcc3100-8c24-11eb-8b77-d04eb390363b.png)

Equip melee gear, and voila, can hit the next rows to finish: 

![image](https://user-images.githubusercontent.com/81268914/112243657-5522fe00-8c24-11eb-8506-4a7488b03cb9.png)

**Comment by geheur** [comment]
Closing this since tooltips are fixed. Opened new issue #10 for scrollbar.
