### ISSUE TITLE
BUG: Plugin broken after While Guthix Sleeps update.

### ISSUE THREAD

**Issue by steven43533** [geheur/bank-tag-custom-layouts#95]
Seems that the latest update completely broke the plugin for me, my layouts aren't saving and I am unable to withdraw items when using the tagged layouts. Also right clicking the items while in the tagged layout seems to be showing duplicate options and at times showing options for a completely different item. 
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/24616638/144edd15-58a8-4190-bdbf-0e714dcab0c6)
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/24616638/71dda3e3-75fa-492a-b977-003e7e81b9f7)

https://github.com/geheur/bank-tag-custom-layouts/assets/24616638/3280f4fc-d116-4359-8649-084df5dc0341

**Comment by joemckie** [comment]
I think this is an interaction between Bank Tag Layouts and Inventory Setups. Unchecking the "Use with Inventory Setups" option allows me to withdraw items, at least.

**Comment by steven43533** [comment]
@joemckie Just tried out what you said and can also confirm that unchecking "Use with Inventory Setups" at least let's me withdraw the items. It also fixes the bug that occurs when you right click an item and have more options than you should or shows options for a completely different item.

Seems like someone already opened an issue about this for Inventory Setups:
https://github.com/dillydill123/inventory-setups/issues/256

**Comment by Steierer420** [comment]
I'm having the same issue... my Bank layout combined with inventory setups plugin is completely broken

**Comment by geheur** [comment]
it should be fixed now. restart client or update BTL.

**Comment by steven43533** [comment]
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/24616638/2b3a7a2d-d0ed-4d2a-9e19-c1c56f8cab17)
Restarted client a couple of times now to make sure I got the latest version. Attempting to create a new setup now causes this to happen for some odd reason.

**Comment by gtjamesa** [comment]
@geheur reverting the change has fixed most of my inventory setups, but some are showing repeated items. Can we provide any info (ie the layouts) to help debug?

![image](https://github.com/geheur/bank-tag-custom-layouts/assets/2078364/a970a77d-45f8-4c24-977c-b718d21e933e)
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/2078364/58e0dbd3-9601-4976-bc5c-c17f0ee8dcf0)
![image](https://github.com/geheur/bank-tag-custom-layouts/assets/2078364/ddda5634-94fd-43c2-9f43-13fcf8e1450d)

**Comment by geheur** [comment]
hmm I'll have a look.

**Comment by geheur** [comment]
The duplicate items are probably from the bug that was fixed. If you have them, remove them.
