### ISSUE TITLE
Cannot Withdraw Items and Custom Layout No Longer Working

### ISSUE THREAD

**Issue by nathanxb** [geheur/bank-tag-custom-layouts#96]
I have a custom layout for every setup I've created, but as of July, 10, 2024 (day of Guthix Sleeps release) these no longer work. Beyond this, when trying to interact with my items, they will not get withdrawn unless I right click and select withdraw.

What my Corp setup looks like now
<img width="455" alt="image" src="https://github.com/geheur/bank-tag-custom-layouts/assets/101832589/b9b500ef-e3c1-49ed-a039-104539731d0c">

Notice, the auto layout button is not there, but if I toggle the setting, it makes it apear. When I click on it, it then shows essentially what I used to have for my layout (aside from random duplicates I didn't make myself like runes, masori, cannonballs, and the extra sharks at the bottom).
<img width="457" alt="image" src="https://github.com/geheur/bank-tag-custom-layouts/assets/101832589/7ed920b6-45bb-4983-a733-e49278e8b8ba">

When I click the check mark, it sort of saves the layout, but then looks like this:
<img width="457" alt="image" src="https://github.com/geheur/bank-tag-custom-layouts/assets/101832589/23bf863d-b169-4c78-8edc-e7e493f08e53">

From here, when I click on the items, I cannot withdraw anything. I have to right click, then click "Withdraw 1". Once I do that once, it withdraws that item, but then I get sent back to this:
<img width="456" alt="image" src="https://github.com/geheur/bank-tag-custom-layouts/assets/101832589/b1f49f50-4d06-41ff-b9f3-096ae6e952a4">

For further info, here's my Bank Tag Layout config:
<img width="120" alt="image" src="https://github.com/geheur/bank-tag-custom-layouts/assets/101832589/02b4da01-9bf0-4e5c-9986-1e8bb773fe59">

I reached out to clan members that also use the plugin and they are experiencing the same issues so I know it is not limited to me. If I can assist further, please let me know.

**Comment by geheur** [comment]
There was a fix recently. try restarting your client?

**Comment by nathanxb** [comment]
> There was a fix recently. try restarting your client?

Just restarted and see that it is fixed now! Thank you. Have some cleaning up to do as there's a million dupes now lol but that's alright.

**Comment by geheur** [comment]
probably easier to remove the item and re-add it.
sorry for the trouble.
