### ISSUE TITLE
Bank tag layout not recognising clues

### ISSUE THREAD

**Issue by pettrs** [geheur/bank-tag-custom-layouts#97]
as mentioned in the title, not sure if this goes for other items too but when I open implings from my clues tab, the tab no longer recognizes that I have a clue of that tier in the tab

https://gyazo.com/95f88090ee1b349531bc494ffed3f8f1

**Comment by geheur** [comment]
There was a change to how runelite sees clues. Add each tier you want back in by holding shift while dragging it on to the tab.
